---
- name: Install Neovim from MilanVives/nvim on Ubuntu AMD64
  hosts: ubuntu-servers
  user: ubuntu
  become: yes

  vars:
    nvim_repo_url: "https://github.com/yourusername/nvim.git"
    nvim_repo_dest: "/tmp/nvim-installer"

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Clone nvim repository
      git:
        repo: "{{ nvim_repo_url }}"
        dest: "{{ nvim_repo_dest }}"
        version: main
        force: yes

    - name: Run Neovim installation script (non-interactive)
      script: "{{ nvim_repo_dest }}/install/install-ubuntu.sh --non-interactive --force-reinstall"
      environment:
        NVIM_NON_INTERACTIVE: "true"
        NVIM_FORCE_REINSTALL: "true"
      register: nvim_install_result
          
    - name: Display installation result
      debug:
        var: nvim_install_result.stdout_lines
        
    - name: Verify Neovim installation
      command: /opt/nvim-linux64/bin/nvim --version
      register: nvim_version
      
    - name: Display Neovim version
      debug:
        msg: "Neovim installed successfully: {{ nvim_version.stdout_lines[0] }}"
        
    - name: Clean up temporary repository
      file:
        path: "{{ nvim_repo_dest }}"
        state: absent